# Generated by Django 4.1 on 2023-06-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thriftapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(max_length=20),
        ),
    ]
