# Generated by Django 4.1 on 2023-06-20 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thriftapp", "0002_alter_product_condition_alter_product_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
