# Generated by Django 4.1 on 2023-06-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thriftapp", "0004_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="MISSING VALUE", upload_to="images"),
        ),
    ]
