# Generated by Django 4.1 on 2023-06-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thriftapp", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                default="MISSING VALUE",
                null=True,
                upload_to="C://Users62811//Project Software Engineer//thriftstore//static//images",
            ),
        ),
    ]
