# Generated by Django 4.1 on 2023-06-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thriftapp", "0006_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(default="MISSING VALUE", upload_to=""),
        ),
    ]
